import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");
const IMAGE_SIZE = (width - 40) / 3;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F6F7F9",
  },
  header: {
    backgroundColor: "#595554",
    width: "100%",
    height: 200,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    overflow: "hidden",
    position: "relative",
  },
  headerBgImage: {
    resizeMode: "cover",
    width: "100%",
    height: "100%",
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  backBtn: {
    backgroundColor: "#F6F7F9",
    borderRadius: 24,
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 0,
    marginLeft: 0,
    zIndex: 2,
    position: "absolute",
    top: 18,
    left: 12,
    shadowColor: "#000",
    shadowOpacity: 0.07,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    elevation: 2,
  },
  centerCameraBtn: {
    position: "absolute",
    top: "40%",
    left: "50%",
    transform: [{ translateX: -48 }, { translateY: -48 }],
    width: 90,
    height: 90,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
    opacity: 1,
  },
  plusIcon: {
    position: "absolute",
    top: 8,
    right: 2,
    opacity: 0.28,
  },
  profileSection: {
    backgroundColor: "#E5ECF6",
    marginTop: -45,
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 8,
    alignItems: "flex-start",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    elevation: 4,
    width: "100%",
    alignSelf: "center",
    zIndex: 2,
  },
  profileRow: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    marginTop: -24,
    marginBottom: 4,
    justifyContent: "flex-start",
  },
  avatarColumn: {
    flexDirection: "column",
    alignItems: "center",
    marginRight: 16,
    marginLeft: 16,
  },
  avatarWrapper: {
    borderWidth: 3,
    borderColor: "#fff",
    borderRadius: 50,
    padding: 1,
    backgroundColor: "#fff",
    marginRight: 48,
    marginTop: -26,
    position: "relative",
  },
  avatar: {
    width: 78,
    height: 78,
    borderRadius: 36,
    backgroundColor: "#E0E0E0",
  },
  profileInfo: {
    alignItems: "flex-start",
    marginTop: 8,
  },
  name: {
    fontWeight: "bold",
    fontSize: 18,
    color: "#222",
    marginTop: 4,
    marginLeft: 0, // ensure no left margin
  },
  username: {
    fontSize: 15,
    color: "#888",
    marginTop: 2,
    marginBottom: 4,
    marginLeft: 0, // changed from -20 to 0
    fontWeight: "500",
  },
  subInfo: {
    fontSize: 13,
    color: "#888",
    marginTop: 2,
    marginLeft: 0, // changed from -20 to 0
  },
  statsColumnFixed: {
    flex: 1,
    alignItems: "flex-end",
    justifyContent: "center",
    marginTop: 45,
    marginRight: 8,
  },
  statsRowFixed: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  statBoxFixed: {
    alignItems: "center",
    marginHorizontal: 6,
  },
  statNumber: {
    fontWeight: "bold",
    fontSize: 18,
    color: "#222",
  },
  statLabel: {
    fontSize: 13,
    color: "#888",
  },
  bioCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f9f9f9",
    borderRadius: 16,
    padding: 14,
    marginTop: 12,
    marginBottom: 8,
    width: "100%",
    alignSelf: "center",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    elevation: 2,
  },
  bioTitle: {
    fontWeight: "bold",
    fontSize: 15,
    color: "#222",
  },
  bioSubtitle: {
    fontSize: 13,
    color: "#888",
  },
  bioText: {
    fontSize: 13.5,
    color: "#526797",
    lineHeight: 21,
    fontWeight: "400",
    textAlign: "justify",
  },
  hometownRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
    marginBottom: 8,
    paddingHorizontal: 10,
    alignSelf: "flex-start",
    backgroundColor: "#f9f9f9",
    borderRadius: 12,
    paddingVertical: 6,
  },
  hometownText: {
    fontSize: 14,
    color: "#888",
    marginLeft: 6,
  },
  postsSection: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    marginTop: 10,
    paddingTop: 10,
    minHeight: 320, // Ensures the section is always at least this tall
  },
  postsHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    marginBottom: 8,
  },
  postsTitle: {
    fontWeight: "bold",
    fontSize: 14,
    color: "#888",
    letterSpacing: 1,
  },
  postsGrid: {
    paddingHorizontal: 0,
    paddingBottom: 20,
  },
  postImage: {
    width: IMAGE_SIZE,
    height: IMAGE_SIZE,
    borderRadius: 12,
    margin: 4,
    backgroundColor: "#E0E0E0",
  },
  postWrapper: {
    flex: 1,
    margin: 4,
    borderRadius: 10,
    overflow: "hidden",
  },
  postContainer: {
    flex: 1,
    borderRadius: 10,
    overflow: "hidden",
    backgroundColor: "#fff",
    elevation: 2, // for Android shadow
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
  },
  editAvatarBtn: {
    position: "absolute",
    bottom: -2,
    right: -8,
    backgroundColor: "#888",
    borderRadius: 16,
    width: 27,
    height: 27,
    alignItems: "center",
    justifyContent: "center",
    padding: 2,
    borderWidth: 2,
    borderColor: "#fff",
    zIndex: 2,
  },
  checkboxContainer: {
    position: "absolute",
    top: 8,
    right: 8,
    zIndex: 10,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: "#ff8c00",
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxSelected: {
    backgroundColor: "#ff8c00",
    borderColor: "#ff8c00",
  },
  editPostsBtn: {
    marginLeft: 6,
    padding: 0,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: "#bbb",
    alignItems: "center",
    justifyContent: "center",
    height: 20,
    width: 22,
    backgroundColor: "transparent",
    overflow: "visible",
  },
  editIconWrapper: {
    position: "absolute",
    top: -7,
    left: 2,
    right: 3,
    alignItems: "center",
    justifyContent: "center",
    height: 30,
  },
  editIcon: {},
  deletePostsBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#e74c3c",
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginLeft: 10,
  },
  deleteIconWrapper: {
    backgroundColor: "#c0392b",
    borderRadius: 12,
    padding: 4,
    marginRight: 6,
  },
  deleteIcon: {
    alignSelf: "center",
  },
  deleteText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 15,
  },
  editableFieldInput: {
    borderColor: "#ddd",
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    backgroundColor: "#fff",
    marginBottom: 10,
  },
  editableFieldInputMultiline: {
    height: 80,
    textAlignVertical: "top",
  },
  editableFieldInputSingle: {
    textAlignVertical: "auto",
  },
  editableFieldCounter: {
    fontSize: 12,
    color: "#666",
    textAlign: "right",
    marginBottom: 15,
  },
  editableFieldBtnRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  editableFieldCancelBtn: {
    flex: 1,
    backgroundColor: "#f5f5f5",
    padding: 12,
    borderRadius: 6,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ddd",
  },
  editableFieldCancelText: {
    color: "#333",
    fontWeight: "600",
    fontSize: 16,
  },
  editableFieldSaveBtn: {
    flex: 1,
    backgroundColor: "#007AFF",
    padding: 12,
    borderRadius: 6,
    alignItems: "center",
  },
  editableFieldSaveBtnDisabled: {
    opacity: 0.7,
  },
  editableFieldSaveText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 16,
  },
  editableFieldRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  hometownInputRow: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  hometownInput: {
    flex: 1,
    borderColor: "#ddd",
    borderWidth: 1,
    borderRadius: 8,
    padding: 8,
    fontSize: 16,
    backgroundColor: "#fff",
  },
  hometownInputBtn: {
    marginLeft: 8,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.18)",
  },
});
