import { StyleSheet, Dimensions } from "react-native";
import { tokens } from "../theme/colors";
import { typography } from "../theme/typography";
import { radius, spacing, elevation } from "../theme/spacing";

const { width } = Dimensions.get("window");
const IMAGE_SIZE = (width - 40) / 3;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: tokens.canvas,
  },
  header: {
    backgroundColor: tokens.primaryTint,
    width: "100%",
    height: 200,
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    overflow: "hidden",
    position: "relative",
  },
  headerBgImage: {
    resizeMode: "cover",
    width: "100%",
    height: "100%",
  },
  backBtn: {
    backgroundColor: tokens.surface,
    borderRadius: radius.pill,
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
    position: "absolute",
    top: 18,
    left: spacing.md,
    ...elevation.raised,
  },
  centerCameraBtn: {
    position: "absolute",
    top: "40%",
    left: "50%",
    transform: [{ translateX: -48 }, { translateY: -48 }],
    width: 90,
    height: 90,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  plusIcon: {
    position: "absolute",
    top: spacing.sm,
    right: 2,
    opacity: 0.28,
  },
  profileSection: {
    backgroundColor: tokens.canvas,
    marginTop: -45,
    borderRadius: radius.xl,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
    alignItems: "flex-start",
    ...elevation.floating,
    width: "100%",
    alignSelf: "center",
    zIndex: 2,
  },
  profileRow: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    marginTop: -24,
    marginBottom: spacing.xs,
    justifyContent: "flex-start",
  },
  avatarColumn: {
    flexDirection: "column",
    alignItems: "center",
    marginRight: spacing.md,
    marginLeft: spacing.md,
  },
  avatarWrapper: {
    borderWidth: 3,
    borderColor: tokens.surface,
    borderRadius: radius.pill,
    padding: 1,
    backgroundColor: tokens.surface,
    marginRight: spacing.xxl,
    marginTop: -26,
    position: "relative",
  },
  avatar: {
    width: 78,
    height: 78,
    borderRadius: 36,
    backgroundColor: tokens.canvas,
  },
  profileInfo: {
    alignItems: "flex-start",
    marginTop: spacing.sm,
  },
  name: {
    ...typography.heading,
    color: tokens.ink900,
    marginTop: spacing.xs,
  },
  username: {
    ...typography.label,
    color: tokens.ink600,
    marginTop: 2,
    marginBottom: spacing.xs,
  },
  subInfo: {
    ...typography.caption,
    color: tokens.ink600,
    marginTop: 2,
  },
  statsColumnFixed: {
    flex: 1,
    alignItems: "flex-end",
    justifyContent: "center",
    marginTop: 45,
    marginRight: spacing.sm,
  },
  statsRowFixed: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  statBoxFixed: {
    alignItems: "center",
    marginHorizontal: spacing.xs,
  },
  statNumber: {
    ...typography.heading,
    color: tokens.ink900,
  },
  statLabel: {
    ...typography.caption,
    color: tokens.ink600,
  },
  bioCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: tokens.surface,
    borderRadius: radius.lg,
    padding: spacing.md,
    marginTop: spacing.md,
    marginBottom: spacing.sm,
    width: "100%",
    alignSelf: "center",
    ...elevation.raised,
  },
  bioTitle: {
    ...typography.heading,
    color: tokens.ink900,
  },
  bioSubtitle: {
    ...typography.caption,
    color: tokens.ink600,
  },
  bioText: {
    ...typography.body,
    color: tokens.ink600,
    lineHeight: 21,
  },
  hometownRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: spacing.sm,
    marginBottom: spacing.sm,
    paddingHorizontal: spacing.sm,
    alignSelf: "flex-start",
    backgroundColor: tokens.surface,
    borderRadius: radius.md,
    paddingVertical: spacing.xs,
  },
  hometownText: {
    ...typography.body,
    color: tokens.ink600,
    marginLeft: spacing.xs,
  },
  postsSection: {
    backgroundColor: tokens.surface,
    borderTopLeftRadius: radius.lg,
    borderTopRightRadius: radius.lg,
    marginTop: spacing.sm,
    paddingTop: spacing.sm,
    minHeight: 320,
  },
  postsHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.lg,
    marginBottom: spacing.sm,
  },
  postsTitle: {
    ...typography.label,
    color: tokens.ink600,
    letterSpacing: 1,
  },
  postsGrid: {
    paddingHorizontal: 0,
    paddingBottom: spacing.xl,
  },
  postImage: {
    width: IMAGE_SIZE,
    height: IMAGE_SIZE,
    borderRadius: radius.md,
    margin: spacing.xs,
    backgroundColor: tokens.canvas,
  },
  postWrapper: {
    flex: 1,
    margin: spacing.xs,
    borderRadius: radius.sm,
    overflow: "hidden",
  },
  postContainer: {
    flex: 1,
    borderRadius: radius.sm,
    overflow: "hidden",
    backgroundColor: tokens.surface,
    ...elevation.raised,
  },
  editAvatarBtn: {
    position: "absolute",
    bottom: -2,
    right: -8,
    backgroundColor: tokens.ink600,
    borderRadius: radius.md,
    width: 27,
    height: 27,
    alignItems: "center",
    justifyContent: "center",
    padding: 2,
    borderWidth: 2,
    borderColor: tokens.surface,
    zIndex: 2,
  },
  checkboxContainer: {
    position: "absolute",
    top: spacing.sm,
    right: spacing.sm,
    zIndex: 10,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: radius.sm,
    borderWidth: 2,
    borderColor: tokens.primary,
    backgroundColor: tokens.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxSelected: {
    backgroundColor: tokens.primary,
    borderColor: tokens.primary,
  },
  editPostsBtn: {
    marginLeft: spacing.xs,
    padding: 0,
    borderRadius: radius.sm,
    borderWidth: 1.5,
    borderColor: tokens.line,
    alignItems: "center",
    justifyContent: "center",
    height: 20,
    width: 22,
    backgroundColor: "transparent",
    overflow: "visible",
  },
  editIconWrapper: {
    position: "absolute",
    top: -7,
    left: 2,
    right: 3,
    alignItems: "center",
    justifyContent: "center",
    height: 30,
  },
  editIcon: {},
  deletePostsBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: tokens.danger,
    borderRadius: radius.sm,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.md,
    marginLeft: spacing.sm,
  },
  deleteIconWrapper: {
    backgroundColor: tokens.danger,
    borderRadius: radius.md,
    padding: spacing.xs,
    marginRight: spacing.xs,
  },
  deleteIcon: {
    alignSelf: "center",
  },
  deleteText: {
    color: "#fff",
    fontWeight: "600",
    ...typography.body,
  },
  editableFieldInput: {
    borderColor: tokens.line,
    borderWidth: 1.5,
    borderRadius: radius.md,
    padding: spacing.md,
    ...typography.body,
    color: tokens.ink900,
    backgroundColor: tokens.surface,
    marginBottom: spacing.sm,
  },
  editableFieldInputMultiline: {
    height: 80,
    textAlignVertical: "top",
  },
  editableFieldInputSingle: {
    textAlignVertical: "auto",
  },
  editableFieldCounter: {
    ...typography.caption,
    color: tokens.ink600,
    textAlign: "right",
    marginBottom: spacing.md,
  },
  editableFieldBtnRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  editableFieldCancelBtn: {
    flex: 1,
    backgroundColor: tokens.canvas,
    padding: spacing.md,
    borderRadius: radius.sm,
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: tokens.line,
  },
  editableFieldCancelText: {
    color: tokens.ink900,
    fontWeight: "600",
    ...typography.body,
  },
  editableFieldSaveBtn: {
    flex: 1,
    backgroundColor: tokens.primary,
    padding: spacing.md,
    borderRadius: radius.sm,
    alignItems: "center",
  },
  editableFieldSaveBtnDisabled: {
    opacity: 0.7,
  },
  editableFieldSaveText: {
    color: "#fff",
    fontWeight: "600",
    ...typography.body,
  },
  editableFieldRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  hometownInputRow: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  hometownInput: {
    flex: 1,
    borderColor: tokens.line,
    borderWidth: 1.5,
    borderRadius: radius.sm,
    padding: spacing.sm,
    ...typography.body,
    color: tokens.ink900,
    backgroundColor: tokens.surface,
  },
  hometownInputBtn: {
    marginLeft: spacing.sm,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.12)",
  },
});
