import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#e5ecf6" },
  scrollContent: {
    flexGrow: 1,
  },
  container: { flex: 1, alignItems: "center", padding: 20 },
  imageArea: {
    width: "100%",
    height: 350,
    borderRadius: 18,
    marginBottom: 24,
    backgroundColor: "#F5F5F5",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
  },
  image: {
    width: "100%",
    height: "100%",
    borderRadius: 18,
    resizeMode: "cover",
  },
  selectButton: {
    width: 180,
    height: 54,
    backgroundColor: "#fff",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#ff9800",
    shadowColor: "#ff9800",
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 8,
    elevation: 6,
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 8,
    flexDirection: "row",
  },
  selectButtonText: { color: "#222", fontSize: 16, fontWeight: "bold" },
  input: {
    width: "100%",
    minHeight: 60,
    borderColor: "#ccc",
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    fontSize: 18,
    backgroundColor: "#fff",
  },
  inputFocused: {
    borderColor: "#FFA500",
    shadowColor: "#FFA500",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.7,
    shadowRadius: 4,
    elevation: 3,
  },
  postButton: {
    width: "80%",
    height: 54,
    backgroundColor: "#FF8C00",
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    marginTop: "auto",
    marginBottom: 24,
  },
  postButtonText: { color: "#fff", fontSize: 20, fontWeight: "bold" },
  closeButton: {
    position: "absolute",
    top: 14,
    right: 14,
    backgroundColor: "rgba(0,0,0,0.45)",
    borderRadius: 18,
    width: 26,
    height: 26,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 2,
  },
  closeButtonText: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "bold",
    lineHeight: 24,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    paddingHorizontal: 16,
    paddingTop: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 4,
    zIndex: 10,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#222",
    marginLeft: 6,
    letterSpacing: 0.5,
  },
  captionCloseButton: {
    position: "absolute",
    top: 12,
    right: 12,
    backgroundColor: "#B0B0B0",
    borderRadius: 18,
    width: 26,
    height: 26,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 2,
  },
  plusBorder: {
    borderWidth: 2,
    borderColor: "#000",
    borderRadius: 22,
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  captionArea: {
    width: "100%",
    marginBottom: 24,
    position: "relative",
    minHeight: 60,
    justifyContent: "center",
  },
});

export default styles;
