import { StyleSheet } from "react-native";
import { tokens } from "../theme/colors";
import { typography } from "../theme/typography";
import { radius, spacing, elevation } from "../theme/spacing";

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: tokens.canvas },
  scrollContent: {
    flexGrow: 1,
  },
  container: { flex: 1, alignItems: "center", padding: spacing.xl },
  imageArea: {
    width: "100%",
    height: 350,
    borderRadius: radius.xl,
    marginBottom: spacing.xl,
    backgroundColor: tokens.surface,
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
    ...elevation.raised,
  },
  image: {
    width: "100%",
    height: "100%",
    borderRadius: radius.xl,
    resizeMode: "cover",
  },
  selectButton: {
    width: 180,
    height: 54,
    backgroundColor: tokens.surface,
    borderRadius: radius.md,
    borderWidth: 1.5,
    borderColor: tokens.line,
    justifyContent: "center",
    alignItems: "center",
    marginVertical: spacing.sm,
    flexDirection: "row",
  },
  selectButtonText: { color: tokens.ink900, ...typography.heading },
  input: {
    width: "100%",
    minHeight: 60,
    borderColor: tokens.line,
    borderWidth: 1.5,
    borderRadius: radius.md,
    padding: spacing.md,
    ...typography.body,
    color: tokens.ink900,
    backgroundColor: tokens.surface,
  },
  inputFocused: {
    borderColor: tokens.primary,
  },
  postButton: {
    width: "80%",
    height: 54,
    backgroundColor: tokens.primary,
    borderRadius: radius.md,
    justifyContent: "center",
    alignItems: "center",
    marginTop: "auto",
    marginBottom: spacing.xl,
  },
  postButtonText: { color: "#fff", fontSize: 20, fontWeight: "bold" },
  closeButton: {
    position: "absolute",
    top: 14,
    right: 14,
    backgroundColor: "rgba(0,0,0,0.45)",
    borderRadius: 18,
    width: 26,
    height: 26,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 2,
  },
  closeButtonText: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "bold",
    lineHeight: 24,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: tokens.surface,
    paddingHorizontal: spacing.lg,
    paddingTop: 0,
    ...elevation.floating,
    zIndex: 10,
  },
  headerTitle: {
    ...typography.title,
    color: tokens.ink900,
    marginLeft: spacing.xs,
  },
  captionCloseButton: {
    position: "absolute",
    top: 12,
    right: 12,
    backgroundColor: tokens.ink400,
    borderRadius: 18,
    width: 26,
    height: 26,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 2,
  },
  plusBorder: {
    borderWidth: 2,
    borderColor: tokens.ink900,
    borderRadius: 22,
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
    marginRight: spacing.sm,
  },
  captionArea: {
    width: "100%",
    marginBottom: spacing.xl,
    position: "relative",
    minHeight: 60,
    justifyContent: "center",
  },
  priceRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    marginBottom: spacing.lg,
    borderColor: tokens.line,
    borderWidth: 1.5,
    borderRadius: radius.md,
    backgroundColor: tokens.surface,
    paddingHorizontal: spacing.md,
  },
  priceRowFocused: {
    borderColor: tokens.primary,
  },
  priceSymbol: {
    fontSize: 18,
    color: tokens.ink600,
    marginRight: spacing.xs,
  },
  priceInput: {
    flex: 1,
    height: 52,
    fontSize: 18,
    color: tokens.ink900,
  },
  priceHint: {
    ...typography.caption,
    color: tokens.ink400,
    marginTop: -14,
    marginBottom: spacing.lg,
    alignSelf: "flex-start",
  },
});

export default styles;
